
(function(){
"use strict";
var $=function(s){return document.querySelector(s)};
var $$=function(s){return Array.prototype.slice.call(document.querySelectorAll(s))};
var DEFAULTS={xp:0,energy:0,coins:0,correct:0,wrongIds:[],cleared:0,stars:{},medals:[],streak:0,lastDay:"",dailyCorrect:0,dailyDone:false,lastAnsweredDay:"",coinLastProcessedDay:""};
var profile={name:"",avatar:"🦊"},selectedAvatar="🦊",state=clone(DEFAULTS);
var session=[],questionIndex=0,correctNow=0,wrongNow=[],currentStage=null,currentMode="stage",selectedChoice=null;
function clone(x){return JSON.parse(JSON.stringify(x))}
function getJSON(key,fallback){try{var raw=localStorage.getItem(key);return raw?JSON.parse(raw):fallback}catch(e){return fallback}}
function setJSON(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true}catch(e){return false}}
function keyFor(name){return "eco_v3_"+encodeURIComponent(name.trim().toLowerCase())}
function loadProfile(){profile=getJSON("eco_v3_active",{name:"",avatar:"🦊"})||{name:"",avatar:"🦊"};selectedAvatar=profile.avatar||"🦊"}
function loadState(){state=Object.assign(clone(DEFAULTS),profile.name?getJSON(keyFor(profile.name),{}):{})}
function registerProfile(){if(!profile.name)return;var list=getJSON("eco_v3_profiles",[]);var key=profile.name.trim().toLowerCase();var found=false;list=list.map(function(x){if((x.name||"").trim().toLowerCase()===key){found=true;return {name:profile.name,avatar:profile.avatar}}return x});if(!found)list.push({name:profile.name,avatar:profile.avatar});setJSON("eco_v3_profiles",list)}
function save(){if(profile.name){setJSON(keyFor(profile.name),state);registerProfile()}renderHome()}
function today(){var d=new Date();return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0")}
function yesterday(){var d=new Date(Date.now()-86400000);return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0")}
function parseDay(s){var p=String(s||"").split("-");return new Date(Number(p[0]),Number(p[1])-1,Number(p[2]))}
function dayString(d){return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0")}
function addDays(s,n){var d=parseDay(s);d.setDate(d.getDate()+n);return dayString(d)}
function processCoinCalendar(){var d=today();if(!state.coinLastProcessedDay){state.coinLastProcessedDay=d;return 0}var cursor=addDays(state.coinLastProcessedDay,1),missed=0;while(cursor<d){if(state.lastAnsweredDay!==cursor){state.coins-=1;missed++}state.coinLastProcessedDay=cursor;cursor=addDays(cursor,1)}return missed}
function awardDailyCoin(){var d=today();if(state.lastAnsweredDay===d)return false;state.lastAnsweredDay=d;state.coins+=1;return true}
function refreshDaily(){var d=today();if(state.lastDay!==d){state.streak=state.lastDay===yesterday()?state.streak+1:1;state.lastDay=d;state.dailyCorrect=0;state.dailyDone=false;save()}}
function level(){return Math.floor(state.xp/100)+1}
function title(){var l=level();return l<3?"見習環保員":l<6?"綠色小隊長":l<10?"地球守護者":"傳說環保英雄"}
function shuffle(a){var x=a.slice();for(var i=x.length-1;i>0;i--){var j=Math.floor(Math.random()*(i+1));var t=x[i];x[i]=x[j];x[j]=t}return x}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,function(c){return {"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]})}
function toast(t){var e=$("#toast");e.textContent=t;e.classList.add("show");setTimeout(function(){e.classList.remove("show")},1700)}
function renderHome(){
 $("#playerName").textContent=profile.name?"守護者 "+profile.name:"守護者";$("#heroSubtitle").textContent=profile.name?profile.name+"的地球守護挑戰":"地球守護挑戰";$("#avatar").textContent=profile.avatar||"🦊";$("#level").textContent="Lv."+level();$("#rankTitle").textContent=title();$("#xpfill").style.width=(state.xp%100)+"%";
 $("#streak").textContent="🔥 連續 "+state.streak+" 天";$("#taskfill").style.width=Math.min(100,state.dailyCorrect*10)+"%";$("#dailyTitle").textContent=state.dailyDone?"今日寶箱已完成！":"答對 10 題，獲得今日寶箱";$("#chest").textContent=state.dailyDone?"✅":"🎁";$("#chest").classList.toggle("ready",!state.dailyDone);$("#chest").setAttribute("aria-label",state.dailyDone?"今日寶箱已完成":"點擊開始今日挑戰");
 $("#coins").textContent=state.coins;$("#energy").textContent=state.energy;$("#medalCount").textContent=state.medals.length;$("#correctTotal").textContent=state.correct;$("#wrongCount").textContent=state.wrongIds.length;$("#worldProgress").textContent=state.cleared+" / 7 關";
 var map=$("#map");map.innerHTML="";CHAPTERS.forEach(function(c){var unlocked=c.id<=state.cleared+1,stars=state.stars[c.id]||0,b=document.createElement("button");b.className="stage "+(unlocked?"unlocked":"locked");b.disabled=!unlocked;b.innerHTML='<div class="stars">'+"★".repeat(stars)+"☆".repeat(3-stars)+'</div><div class="stage-icon">'+c.icon+'</div><h3>第 '+c.id+' 關｜'+c.name+'</h3><p>'+c.desc+'</p><div class="stage-state">'+(unlocked?"挑戰 ▶":"🔒")+'</div>';b.onclick=function(){startStage(c)};map.appendChild(b)})
}
function showOnly(id){["home","quiz","result","medalPage","leaderboardPage"].forEach(function(x){$("#"+x).classList.toggle("hidden",x!==id)});window.scrollTo(0,0)}
function pick(levels,n){return shuffle(BANK.filter(function(q){return levels.indexOf(q.level)>=0})).slice(0,n)}
function startStage(c){currentStage=c;currentMode="stage";session=pick(c.levels,10);begin()}
function startDaily(){currentStage={id:0,name:"今日任務",icon:"🎯",boss:"每日挑戰怪獸",monster:"👾",levels:["初級","中級","中高級","高級"]};currentMode="daily";session=pick(currentStage.levels,10);begin()}
function startWrong(){var ids=new Set(state.wrongIds),items=shuffle(BANK.filter(function(q){return ids.has(q.id)})).slice(0,20);if(!items.length){toast("目前沒有錯題，太厲害了！");return}currentStage={id:-1,name:"怪獸弱點筆記",icon:"📒",boss:"錯題怪獸",monster:"🧠"};currentMode="wrong";session=items;begin()}
function begin(){questionIndex=0;correctNow=0;wrongNow=[];showOnly("quiz");showQuestion()}
function showQuestion(){var q=session[questionIndex];selectedChoice=null;$("#counter").textContent=(questionIndex+1)+" / "+session.length;$("#progressfill").style.width=(questionIndex/session.length*100)+"%";$("#stageBadge").textContent=currentStage.icon+" "+currentStage.name;$("#monster").textContent=currentStage.monster||"👾";$("#bossName").textContent=currentStage.boss||"環境怪獸";$("#hpfill").style.width=((session.length-questionIndex)/session.length*100)+"%";$("#question").textContent=q.q;$("#feedback").className="feedback hidden";$("#nextBtn").classList.add("hidden");$("#submitBtn").classList.remove("hidden");$("#submitBtn").disabled=true;var box=$("#options");box.innerHTML="";q.opts.forEach(function(opt,i){var b=document.createElement("button");b.className="option";b.innerHTML='<span class="letter">'+"ABCD"[i]+'</span><span>'+escapeHtml(opt)+'</span>';b.onclick=function(){selectAnswer(i,b)};box.appendChild(b)})}
function selectAnswer(choice,button){selectedChoice=choice;$$('.option').forEach(function(b){b.classList.remove("selected")});button.classList.add("selected");$("#submitBtn").disabled=false}
function submitAnswer(){if(selectedChoice===null){toast("請先選擇一個答案喔 😊");return}answer(selectedChoice,$$('.option')[selectedChoice])}
function answer(choice,button){var q=session[questionIndex],buttons=$$(".option"),ok=choice===q.ans,coinEarned=awardDailyCoin();buttons.forEach(function(b){b.disabled=true;b.classList.remove("selected")});$("#submitBtn").classList.add("hidden");buttons[q.ans].classList.add("correct");if(ok){correctNow++;state.correct++;state.energy+=10;state.xp+=12;state.dailyCorrect++;state.wrongIds=state.wrongIds.filter(function(id){return id!==q.id});$("#monster").classList.add("hit");setTimeout(function(){$("#monster").classList.remove("hit")},350);toast((coinEarned?"今日答題金幣 +1 🪙｜":"")+"地球能量 +10 ⚡")}else{button.classList.add("wrong");wrongNow.push(q);if(state.wrongIds.indexOf(q.id)<0)state.wrongIds.push(q.id);if(coinEarned)toast("今日答題金幣 +1 🪙")}var f=$("#feedback");f.className="feedback "+(ok?"correct":"wrong");f.innerHTML="<b>"+(ok?"命中怪獸弱點！太棒了 🎉":"沒關係，已記進怪獸弱點筆記 📒")+"</b><div>"+escapeHtml(q.exp)+"</div>";$("#nextBtn").textContent=questionIndex===session.length-1?"領取戰利品":"繼續戰鬥";$("#nextBtn").classList.remove("hidden");$("#progressfill").style.width=((questionIndex+1)/session.length*100)+"%";save()}
function next(){if(questionIndex<session.length-1){questionIndex++;showQuestion();window.scrollTo(0,0)}else finish()}
function finish(){var rate=Math.round(correctNow/session.length*100),stars=rate>=90?3:rate>=70?2:rate>=50?1:0,rank=rate>=90?"S":rate>=80?"A":rate>=70?"B":rate>=60?"C":"再試一次";if(currentMode==="stage"){state.stars[currentStage.id]=Math.max(state.stars[currentStage.id]||0,stars);if(stars>=1&&currentStage.id===state.cleared+1)state.cleared=Math.min(7,state.cleared+1);var medal=currentStage.icon+currentStage.name+"徽章";if(stars===3&&state.medals.indexOf(medal)<0)state.medals.push(medal)}if(currentMode==="daily"&&!state.dailyDone&&state.dailyCorrect>=10){state.dailyDone=true;state.energy+=50;state.xp+=40;if(state.medals.indexOf("🎁 每日任務徽章")<0)state.medals.push("🎁 每日任務徽章")}save();$("#rank").textContent=rank;$("#loot").textContent=stars===3?"🏆✨":stars===2?"🥈🌟":stars===1?"🥉":"🌱";$("#resultTitle").textContent=currentStage.name+"完成！";$("#resultText").textContent="答對 "+correctNow+" / "+session.length+" 題，獲得 "+(correctNow*10)+" 點地球能量。"+(wrongNow.length?"錯題筆記新增 "+wrongNow.length+" 題。":"全數答對，完美守護！");showOnly("result")}
function openProfile(canCancel){$("#profileModal").classList.remove("hidden");$("#cancelProfile").classList.toggle("hidden",!canCancel);$("#nameInput").value=canCancel?profile.name:"";selectedAvatar=canCancel?(profile.avatar||"🦊"):"🦊";$$('.avatar-choice').forEach(function(b){b.classList.toggle("selected",b.dataset.avatar===selectedAvatar)})}
function confirmProfile(){var name=$("#nameInput").value.trim();if(!name){toast("請先輸入守護者名字");return}profile={name:name,avatar:selectedAvatar};setJSON("eco_v3_active",profile);loadState();var missed=processCoinCalendar();$("#profileModal").classList.add("hidden");refreshDaily();save();toast(missed>0?"有 "+missed+" 天沒有答題，守護金幣 -"+missed+" 🪙":"歡迎，守護者 "+name+"！")}
function showLeaderboard(){var list=getJSON("eco_v3_profiles",[]);if(profile.name&&!list.some(function(x){return (x.name||"").toLowerCase()===profile.name.toLowerCase()})){list.push(profile)}var rows=list.map(function(x){var s=Object.assign(clone(DEFAULTS),getJSON(keyFor(x.name),{}));return {name:x.name,avatar:x.avatar||"🦊",energy:s.energy||0,coins:Number(s.coins||0),xp:s.xp||0,correct:s.correct||0,level:Math.floor((s.xp||0)/100)+1}}).sort(function(a,b){return b.energy-a.energy||b.xp-a.xp||b.correct-a.correct||a.name.localeCompare(b.name,"zh-Hant")});var box=$("#leaderboard");if(!rows.length){box.innerHTML="<p>目前還沒有守護者紀錄。</p>"}else{box.innerHTML=rows.map(function(r,i){return '<div class="leader-row '+(r.name===profile.name?'me':'')+'"><div class="place">'+(i===0?'🥇':i===1?'🥈':i===2?'🥉':'第 '+(i+1)+' 名')+'</div><div class="leader-avatar">'+r.avatar+'</div><div class="leader-name"><b>'+escapeHtml(r.name)+'</b><small>Lv.'+r.level+'・累積答對 '+r.correct+' 題・🪙 '+r.coins+'</small></div><div class="leader-score"><b>'+r.energy+'</b><small>地球能量</small></div></div>'}).join("")}showOnly("leaderboardPage")}
function showMedals(){var box=$("#medals");box.innerHTML=state.medals.length?state.medals.map(function(x){return '<div class="medal">'+escapeHtml(x)+'</div>'}).join(""):"<p>關卡取得 3 顆星，就能獲得專屬徽章。</p>";showOnly("medalPage")}
function init(){loadProfile();loadState();$$('.avatar-choice').forEach(function(b){b.onclick=function(){selectedAvatar=b.dataset.avatar;$$('.avatar-choice').forEach(function(x){x.classList.toggle("selected",x===b)})}});$("#saveProfile").onclick=confirmProfile;$("#cancelProfile").onclick=function(){$("#profileModal").classList.add("hidden")};$("#switchProfile").onclick=function(){openProfile(true)};$("#dailyBtn").onclick=startDaily;$("#chest").onclick=function(){if(state.dailyDone){toast("今天的寶箱已經領取囉！明天再來挑戰 🎉")}else{startDaily()}};$("#wrongBtn").onclick=startWrong;$("#submitBtn").onclick=submitAnswer;$("#nextBtn").onclick=next;$("#quitBtn").onclick=function(){showOnly("home")};$("#homeBtn").onclick=function(){showOnly("home")};$("#againBtn").onclick=function(){if(currentMode==="daily")startDaily();else if(currentMode==="wrong")startWrong();else startStage(currentStage)};$("#medalBtn").onclick=showMedals;$("#leaderboardBtn").onclick=showLeaderboard;$("#leaderboardBack").onclick=function(){showOnly("home")};$("#medalBack").onclick=function(){showOnly("home")};$("#resetBtn").onclick=function(){if(confirm("確定要清除這位守護者的所有進度嗎？")){state=clone(DEFAULTS);save();refreshDaily();toast("冒險重新開始了！")}};registerProfile();if(!profile.name){renderHome();openProfile(false)}else{var missed=processCoinCalendar();refreshDaily();save();if(missed>0)toast("有 "+missed+" 天沒有答題，守護金幣 -"+missed+" 🪙")}}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
})();
